import { TrainingProgram } from "@/types/TrainingProgram/TrainingProgram";

export const muravevTrainingProgram: TrainingProgram = {
  id: "Muravev_Training_Program",
  name: "Муравьев (жим лежа)",
  trainingDays: [
    {
      trainingNumber: 1,
      exercises: [
        {
          name: "Жим лежа (62,5%)",
          weight: (maxWeight) => maxWeight * 0.625,
          count: 3,
          reps: 8,
          passed: false,
        },
        {
          name: "Жим лежа с паузой (67,5%)",
          weight: (maxWeight) => maxWeight * 0.675,
          count: 1,
          reps: 1,
          passed: false,
        },
      ],
    },
    {
      trainingNumber: 2,
      exercises: [
        {
          name: "Жим лежа (62,5%)",
          weight: (maxWeight) => maxWeight * 0.625,
          count: 1,
          reps: 5,
          passed: false,
        },
        {
          name: "Жим лежа (70%). Последнее повторение с паузой",
          weight: (maxWeight) => maxWeight * 0.7,
          count: 1,
          reps: 5,
          passed: false,
        },
        {
          name: "Жим лежа (75%)",
          weight: (maxWeight) => maxWeight * 0.75,
          count: 5,
          reps: 5,
          passed: false,
        },
      ],
    },
    {
      trainingNumber: 3,
      exercises: [
        {
          name: "Жим лежа (62,5%)",
          weight: (maxWeight) => maxWeight * 0.625,
          count: 1,
          reps: 5,
          passed: false,
        },
        {
          name: "Жим лежа (70%). Последнее повторение с паузой",
          weight: (maxWeight) => maxWeight * 0.7,
          count: 1,
          reps: 5,
          passed: false,
        },
        {
          name: "Жим лежа (77.5%)",
          weight: (maxWeight) => maxWeight * 0.775,
          count: 3,
          reps: 5,
          passed: false,
        },
      ],
    },
    {
      trainingNumber: 4,
      exercises: [
        {
          name: "Жим лежа (62,5%)",
          weight: (maxWeight) => maxWeight * 0.625,
          count: 1,
          reps: 5,
          passed: false,
        },
        {
          name: "Жим лежа (72.5%). Последнее повторение с паузой",
          weight: (maxWeight) => maxWeight * 0.725,
          count: 1,
          reps: 3,
          passed: false,
        },
        {
          name: "Жим лежа (77.5%)",
          weight: (maxWeight) => maxWeight * 0.775,
          count: 1,
          reps: 3,
          passed: false,
        },
        {
          name: "Жим лежа (82.5%)",
          weight: (maxWeight) => maxWeight * 0.825,
          count: 4,
          reps: 3,
          passed: false,
        },
      ],
    },
    {
      trainingNumber: 5,
      exercises: [
        {
          name: "Жим лежа (62,5%)",
          weight: (maxWeight) => maxWeight * 0.625,
          count: 1,
          reps: 8,
          passed: false,
        },
        {
          name: "Жим лежа (67.5%)",
          weight: (maxWeight) => maxWeight * 0.675,
          count: 4,
          reps: 8,
          passed: false,
        },
        {
          name: "Жим лежа с паузой (72.5%)",
          weight: (maxWeight) => maxWeight * 0.725,
          count: 1,
          reps: 1,
          passed: false,
        },
      ],
    },
    {
      trainingNumber: 6,
      exercises: [
        {
          name: "Жим лежа (62,5%)",
          weight: (maxWeight) => maxWeight * 0.625,
          count: 1,
          reps: 5,
          passed: false,
        },
        {
          name: "Жим лежа (72.5%)",
          weight: (maxWeight) => maxWeight * 0.725,
          count: 1,
          reps: 5,
          passed: false,
        },
        {
          name: "Жим лежа с паузой (75%)",
          weight: (maxWeight) => maxWeight * 0.75,
          count: 1,
          reps: 1,
          passed: false,
        },
        {
          name: "Жим лежа с паузой (77.5%)",
          weight: (maxWeight) => maxWeight * 0.775,
          count: 4,
          reps: 5,
          passed: false,
        },
      ],
    },
    {
      trainingNumber: 7,
      exercises: [
        {
          name: "Жим лежа (62,5%)",
          weight: (maxWeight) => maxWeight * 0.625,
          count: 1,
          reps: 5,
          passed: false,
        },
        {
          name: "Жим лежа (72.5%)",
          weight: (maxWeight) => maxWeight * 0.725,
          count: 1,
          reps: 5,
          passed: false,
        },
        {
          name: "Жим лежа с паузой (75%)",
          weight: (maxWeight) => maxWeight * 0.75,
          count: 1,
          reps: 1,
          passed: false,
        },
        {
          name: "Жим лежа (80%)",
          weight: (maxWeight) => maxWeight * 0.8,
          count: 4,
          reps: 5,
          passed: false,
        },
      ],
    },
    {
      trainingNumber: 8,
      exercises: [
        {
          name: "Жим лежа (62,5%)",
          weight: (maxWeight) => maxWeight * 0.625,
          count: 1,
          reps: 5,
          passed: false,
        },
        {
          name: "Жим лежа (72.5%)",
          weight: (maxWeight) => maxWeight * 0.725,

          count: 1,
          reps: 2,
          passed: false,
        },
        {
          name: "Жим лежа с паузой (75%)",
          weight: (maxWeight) => maxWeight * 0.75,
          count: 1,
          reps: 1,
          passed: false,
        },
        {
          name: "Жим лежа (77.5%)",
          weight: (maxWeight) => maxWeight * 0.775,
          count: 1,
          reps: 2,
          passed: false,
        },
        {
          name: "Жим лежа (82.5%)",
          weight: (maxWeight) => maxWeight * 0.825,
          count: 1,
          reps: 2,
          passed: false,
        },
        {
          name: "Жим лежа (85%)",
          weight: (maxWeight) => maxWeight * 0.85,
          count: 3,
          reps: 2,
          passed: false,
        },
      ],
    },
    {
      trainingNumber: 9,
      exercises: [
        {
          name: "Жим лежа (62,5%)",
          weight: (maxWeight) => maxWeight * 0.625,
          count: 3,
          reps: 8,
          passed: false,
        },
        {
          name: "Жим лежа (70%)",
          weight: (maxWeight) => maxWeight * 0.7,
          count: 4,
          reps: 8,
          passed: false,
        },
        {
          name: "Жим лежа с паузой (77.5%)",
          weight: (maxWeight) => maxWeight * 0.775,
          count: 1,
          reps: 1,
          passed: false,
        },
      ],
    },
    {
      trainingNumber: 10,
      exercises: [
        {
          name: "Жим лежа (62,5%)",
          weight: (maxWeight) => maxWeight * 0.625,
          count: 1,
          reps: 5,
          passed: false,
        },
        {
          name: "Жим лежа (72.5%)",
          weight: (maxWeight) => maxWeight * 0.725,
          count: 1,
          reps: 5,
          passed: false,
        },
        {
          name: "Жим лежа с паузой (77.5%)",
          weight: (maxWeight) => maxWeight * 0.775,
          count: 1,
          reps: 1,
          passed: false,
        },
        {
          name: "Жим лежа (80%)",
          weight: (maxWeight) => maxWeight * 0.8,
          count: 4,
          reps: 5,
          passed: false,
        },
      ],
    },
    {
      trainingNumber: 11,
      exercises: [
        {
          name: "Жим лежа (62,5%)",
          weight: (maxWeight) => maxWeight * 0.625,
          count: 1,
          reps: 5,
          passed: false,
        },
        {
          name: "Жим лежа (72.5%)",
          weight: (maxWeight) => maxWeight * 0.725,
          count: 1,
          reps: 5,
          passed: false,
        },
        {
          name: "Жим лежа (80%). Последний раз в каждом подходе с паузой",
          weight: (maxWeight) => maxWeight * 0.8,
          count: 4,
          reps: 5,
          passed: false,
        },
      ],
    },
    {
      trainingNumber: 12,
      exercises: [
        {
          name: "Жим лежа (62,5%)",
          weight: (maxWeight) => maxWeight * 0.625,
          count: 1,
          reps: 5,
          passed: false,
        },
        {
          name: "Жим лежа (72.5%)",
          weight: (maxWeight) => maxWeight * 0.725,
          count: 1,
          reps: 3,
          passed: false,
        },
        {
          name: "Жим лежа (80%). Последний раз с паузой",
          weight: (maxWeight) => maxWeight * 0.8,
          count: 1,
          reps: 3,
          passed: false,
        },
        {
          name: "Жим лежа (85%)",
          weight: (maxWeight) => maxWeight * 0.85,
          count: 3,
          reps: 3,
          passed: false,
        },
      ],
    },
    {
      trainingNumber: 13,
      exercises: [
        {
          name: "Жим лежа (62,5%)",
          weight: (maxWeight) => maxWeight * 0.625,
          count: 1,
          reps: 8,
          passed: false,
        },
        {
          name: "Жим лежа (72.5%)",
          weight: (maxWeight) => maxWeight * 0.725,
          count: 4,
          reps: 8,
          passed: false,
        },
        {
          name: "Жим лежа с паузой(82.5%)",
          weight: (maxWeight) => maxWeight * 0.825,
          count: 1,
          reps: 1,
          passed: false,
        },
      ],
    },
    {
      trainingNumber: 14,
      exercises: [
        {
          name: "Жим лежа (62,5%)",
          weight: (maxWeight) => maxWeight * 0.625,
          count: 1,
          reps: 5,
          passed: false,
        },
        {
          name: "Жим лежа (72.5%)",
          weight: (maxWeight) => maxWeight * 0.725,
          count: 1,
          reps: 5,
          passed: false,
        },
        {
          name: "Жим лежа (80%)",
          weight: (maxWeight) => maxWeight * 0.8,
          count: 4,
          reps: 5,
          passed: false,
        },
        {
          name: "Жим лежа с паузой(82.5%)",
          weight: (maxWeight) => maxWeight * 0.825,
          count: 1,
          reps: 1,
          passed: false,
        },
      ],
    },
    {
      trainingNumber: 15,
      exercises: [
        {
          name: "Жим лежа (62,5%)",
          weight: (maxWeight) => maxWeight * 0.625,
          count: 1,
          reps: 5,
          passed: false,
        },
        {
          name: "Жим лежа (72.5%)",
          weight: (maxWeight) => maxWeight * 0.725,
          count: 1,
          reps: 5,
          passed: false,
        },
        {
          name: "Жим лежа (82.5%)",
          weight: (maxWeight) => maxWeight * 0.825,
          count: 3,
          reps: 5,
          passed: false,
        },
        {
          name: "Жим лежа с паузой(85%)",
          weight: (maxWeight) => maxWeight * 0.85,
          count: 1,
          reps: 1,
          passed: false,
        },
      ],
    },
    {
      trainingNumber: 16,
      exercises: [
        {
          name: "Жим лежа (62,5%)",
          weight: (maxWeight) => maxWeight * 0.625,
          count: 1,
          reps: 5,
          passed: false,
        },
        {
          name: "Жим лежа (72.5%)",
          weight: (maxWeight) => maxWeight * 0.725,
          count: 1,
          reps: 5,
          passed: false,
        },
        {
          name: "Жим лежа с паузой (85%)",
          weight: (maxWeight) => maxWeight * 0.85,
          count: 1,
          reps: 1,
          passed: false,
        },
        {
          name: "Жим лежа с паузой(87.5%)",
          weight: (maxWeight) => maxWeight * 0.875,
          count: 3,
          reps: 2,
          passed: false,
        },
      ],
    },
    {
      trainingNumber: 17,
      exercises: [
        {
          name: "Жим лежа (65%)",
          weight: (maxWeight) => maxWeight * 0.65,
          count: 1,
          reps: 8,
          passed: false,
        },
        {
          name: "Жим лежа (75%)",
          weight: (maxWeight) => maxWeight * 0.75,
          count: 4,
          reps: 8,
          passed: false,
        },
        {
          name: "Жим лежа с паузой (87.5%)",
          weight: (maxWeight) => maxWeight * 0.875,
          count: 1,
          reps: 1,
          passed: false,
        },
      ],
    },
    {
      trainingNumber: 18,
      exercises: [
        {
          name: "Жим лежа (62.5%)",
          weight: (maxWeight) => maxWeight * 0.625,
          count: 1,
          reps: 5,
          passed: false,
        },
        {
          name: "Жим лежа (72.5%)",
          weight: (maxWeight) => maxWeight * 0.725,
          count: 1,
          reps: 5,
          passed: false,
        },
        {
          name: "Жим лежа (82.5%)",
          weight: (maxWeight) => maxWeight * 0.825,
          count: 3,
          reps: 5,
          passed: false,
        },
        {
          name: "Жим лежа с паузой (87.5%)",
          weight: (maxWeight) => maxWeight * 0.875,
          count: 1,
          reps: 1,
          passed: false,
        },
      ],
    },
    {
      trainingNumber: 19,
      exercises: [
        {
          name: "Жим лежа (62.5%)",
          weight: (maxWeight) => maxWeight * 0.625,
          count: 1,
          reps: 5,
          passed: false,
        },
        {
          name: "Жим лежа (72.5%)",
          weight: (maxWeight) => maxWeight * 0.725,
          count: 1,
          reps: 5,
          passed: false,
        },
        {
          name: "Жим лежа (85%)",
          weight: (maxWeight) => maxWeight * 0.85,
          count: 3,
          reps: 5,
          passed: false,
        },
        {
          name: "Жим лежа с паузой (90%)",
          weight: (maxWeight) => maxWeight * 0.9,
          count: 1,
          reps: 1,
          passed: false,
        },
      ],
    },
    {
      trainingNumber: 20,
      exercises: [
        {
          name: "Жим лежа (65%)",
          weight: (maxWeight) => maxWeight * 0.65,
          count: 1,
          reps: 5,
          passed: false,
        },
        {
          name: "Жим лежа (75%)",
          weight: (maxWeight) => maxWeight * 0.75,
          count: 1,
          reps: 3,
          passed: false,
        },
        {
          name: "Жим лежа (85%)",
          weight: (maxWeight) => maxWeight * 0.85,
          count: 1,
          reps: 3,
          passed: false,
        },
        {
          name: "Жим лежа (87.5%)",
          weight: (maxWeight) => maxWeight * 0.875,

          count: 2,
          reps: 3,
          passed: false,
        },
        {
          name: "Жим лежа с паузой(90%)",
          weight: (maxWeight) => maxWeight * 0.9,
          count: 1,
          reps: 1,
          passed: false,
        },
      ],
    },
    {
      trainingNumber: 21,
      exercises: [
        {
          name: "Жим лежа (65%)",
          weight: (maxWeight) => maxWeight * 0.65,
          count: 1,
          reps: 5,
          passed: false,
        },
        {
          name: "Жим лежа (75%)",
          weight: (maxWeight) => maxWeight * 0.75,
          count: 1,
          reps: 5,
          passed: false,
        },
        {
          name: "Жим лежа (85%)",
          weight: (maxWeight) => maxWeight * 0.85,
          count: 3,
          reps: 5,
          passed: false,
        },
        {
          name: "Жим лежа с паузой(90%)",
          weight: (maxWeight) => maxWeight * 0.9,
          count: 1,
          reps: 1,
          passed: false,
        },
      ],
    },
    {
      trainingNumber: 22,
      exercises: [
        {
          name: "Жим лежа (65%)",
          weight: (maxWeight) => maxWeight * 0.65,
          count: 1,
          reps: 5,
          passed: false,
        },
        {
          name: "Жим лежа (75%)",
          weight: (maxWeight) => maxWeight * 0.75,
          count: 1,
          reps: 5,
          passed: false,
        },
        {
          name: "Жим лежа (85%)",
          weight: (maxWeight) => maxWeight * 0.85,
          count: 1,
          reps: 2,
          passed: false,
        },
        {
          name: "Жим лежа (90%)",
          weight: (maxWeight) => maxWeight * 0.9,
          count: 3,
          reps: 2,
          passed: false,
        },
        {
          name: "Жим лежа с паузой(92.5%)",
          weight: (maxWeight) => maxWeight * 0.925,
          count: 1,
          reps: 1,
          passed: false,
        },
      ],
    },
    {
      trainingNumber: 23,
      exercises: [
        {
          name: "Жим лежа (65%)",
          weight: (maxWeight) => maxWeight * 0.65,
          count: 1,
          reps: 5,
          passed: false,
        },
        {
          name: "Жим лежа (75%)",
          weight: (maxWeight) => maxWeight * 0.75,
          count: 1,
          reps: 3,
          passed: false,
        },
        {
          name: "Жим лежа (85%)",
          weight: (maxWeight) => maxWeight * 0.85,
          count: 1,
          reps: 1,
          passed: false,
        },
        {
          name: "Жим лежа c паузой (87.5%)",
          weight: (maxWeight) => maxWeight * 0.875,
          count: 1,
          reps: 3,
          passed: false,
        },
        {
          name: "Жим лежа (90%)",
          weight: (maxWeight) => maxWeight * 0.9,
          count: 1,
          reps: 1,
          passed: false,
        },
        {
          name: "Жим лежа с паузой(92.5%)",
          weight: (maxWeight) => maxWeight * 0.925,
          count: 1,
          reps: 1,
          passed: false,
        },
        {
          name: "Жим лежа (95%)",
          weight: (maxWeight) => maxWeight * 0.95,
          count: 1,
          reps: 1,
          passed: false,
        },
      ],
    },
  ],
};
