import { ExercisesEnum } from "@/types/Exercises/Exercises";
import { TrainingProgram } from "@/types/TrainingProgram/TrainingProgram";

export const uncleMishaTrainingProgram: TrainingProgram = {
  id: "Dyadya_Misha",
  name: "Тренировочная программа №2 (жим лежа)",
  information: {
    description: "Программа для увеличения силы в жиме лежа",
  },
  trainingDays: [
    {
      trainingNumber: 1,
      exercises: [
        {
          name: "Жим Лежа (65 %)",
          maxWeightCoef: 0.65,
          passed: false,
          reps: 10,
          count: 3,
          type: ExercisesEnum.BENCH_PRESS,
        },
        {
          name: "Сведения сидя",
          passed: false,
          reps: 10,
          count: 3,
          type: ExercisesEnum.SVEDENIYA_SIDYA,
        },
        {
          name: "Тяга верхнего блока",
          passed: false,
          reps: 10,
          count: 4,
          type: ExercisesEnum.TYGA_VERHNEGO_BLOCKA,
        },
        {
          name: "Хаммер",
          passed: false,
          reps: [9, 9, 8, 8, 6],
          count: 4,
          type: ExercisesEnum.HAMMER,
        },
        {
          name: "Тачка (подтягивания в тренажере)",
          passed: false,
          reps: "max",
          count: 4,
          type: ExercisesEnum.PODTYAGIVANIA_V_TRENAZHERE,
        },
        {
          name: "Поднятие штанги на бицепс",
          passed: false,
          reps: [12, 10, 10, 8],
          count: 4,
          type: ExercisesEnum.PODNYATIE_SHTANGI_NA_BICEPS,
        },
      ],
    },
    {
      trainingNumber: 2,
      exercises: [
        {
          name: "Жим Лежа (75 %)",
          maxWeightCoef: 0.75,
          passed: false,
          reps: 5,
          count: 6,
          type: ExercisesEnum.BENCH_PRESS,
        },
        {
          name: "Разводка 35",
          passed: false,
          reps: 12,
          count: 2,
          type: ExercisesEnum.RAZVODKA_GANTELEI_35_DEG,
        },
        {
          name: "Жим ногами",
          passed: false,
          reps: 12,
          count: 4,
          type: ExercisesEnum.ZHIM_NOGAMI,
        },
        {
          name: "Сгибания ног лежа",
          passed: false,
          reps: 10,
          count: 3,
          type: ExercisesEnum.ZGIBANIE_NOG_LEZHA,
        },
        {
          name: "Бицепс со штангой",
          passed: false,
          reps: [12, 10, 8, 8],
          count: 4,
          type: ExercisesEnum.PODNYATIE_SHTANGI_NA_BICEPS,
        },
        {
          name: "Тачка (подтягивания в тренажере)",
          passed: false,
          reps: 12,
          count: 4,
          type: ExercisesEnum.PODTYAGIVANIA_V_TRENAZHERE,
        },
      ],
    },
    {
      trainingNumber: 3,
      exercises: [
        {
          name: "Жим Лежа (85 %)",
          maxWeightCoef: 0.85,
          passed: false,
          reps: 3,
          count: 10,
          type: ExercisesEnum.BENCH_PRESS,
        },
        {
          name: "Сведения сидя",
          count: 2,
          type: ExercisesEnum.SVEDENIYA_SIDYA,
          passed: false,
          reps: 12,
        },
        {
          name: "Жим гантелей сидя",
          count: 4,
          type: ExercisesEnum.ZHIM_GANTELEI_SIDYA,
          passed: false,
          reps: [10, 8, 8, 8],
        },
        {
          name: "Хаммер",
          count: 5,
          type: ExercisesEnum.HAMMER,
          passed: false,
          reps: 10,
        },
        {
          name: "Тяга нижнего блока обратным хватом",
          count: 4,
          type: ExercisesEnum.TYAGA_NIZHNEGO_BLOCKA_OBRATNIM_HVATOM,
          passed: false,
          reps: 10,
        },
        {
          name: "Бицепс со штангой",
          count: 5,
          type: ExercisesEnum.PODNYATIE_SHTANGI_NA_BICEPS,
          passed: false,
          reps: 10,
        },
      ],
    },
    {
      trainingNumber: 4,
      exercises: [
        {
          name: "Жим Лежа (65% + 5кг)",
          maxWeightCoef: 0.65 + 5,
          passed: false,
          reps: 3,
          count: 10,
          type: ExercisesEnum.BENCH_PRESS,
        },
        {
          name: "Разводка (ровно)",
          count: 3,
          type: ExercisesEnum.RAZVODKA_GANTELEI,
          passed: false,
          reps: 10,
        },
        {
          name: "Приседания со штангой",
          count: 4,
          type: ExercisesEnum.SQUATS,
          passed: false,
          reps: 15,
        },
        {
          name: "Разводка ног сидя",
          count: 4,
          type: ExercisesEnum.RAZVODKA_NOG_SIDYA,
          passed: false,
          reps: 10,
        },
        {
          name: "Разводка гантелей",
          count: 4,
          type: ExercisesEnum.RAZVODKA_GANTELEI,
          passed: false,
          reps: 8,
        },
        {
          name: "Разводка гантелей в наклоне",
          count: 4,
          type: ExercisesEnum.RAZVODKA_GANTELEI_V_NAKLONE,
          passed: false,
          reps: 10,
        },
      ],
    },
    {
      trainingNumber: 5,
      exercises: [
        {
          name: "Жим Лежа (75% + 5кг)",
          maxWeightCoef: 0.75 + 5,
          passed: false,
          reps: 6,
          count: 5,
          type: ExercisesEnum.BENCH_PRESS,
        },
        {
          name: "Сведения сидя",
          count: 3,
          type: ExercisesEnum.SVEDENIYA_SIDYA,
          passed: false,
          reps: [10, 10, 8, 8],
        },
        {
          name: "Тяга штанги в наклоне",
          count: 4,
          type: ExercisesEnum.TYAGA_SHTANGI_V_NAKLONE,
          passed: false,
          reps: [10, 10, 8, 8],
        },
        {
          name: "Тяга нижнего блока обратным хватом",
          count: 4,
          type: ExercisesEnum.TYAGA_NIZHNEGO_BLOCKA_OBRATNIM_HVATOM,
          passed: false,
          reps: [12, 12, 10, 10],
        },
        {
          name: "Тачка (подтягивания в тренажере)",
          count: 4,
          type: ExercisesEnum.PODTYAGIVANIA_V_TRENAZHERE,
          passed: false,
          reps: "max",
        },
        {
          name: "Бицепс",
          count: 5,
          type: ExercisesEnum.BICEPS_21,
          passed: false,
          reps: [10, 8, 8, 6, 6],
        },
      ],
    },
    {
      trainingNumber: 6,
      exercises: [
        {
          name: "Жим Лежа (85% + 5кг)",
          maxWeightCoef: 0.85 + 5,
          count: 10,
          type: ExercisesEnum.BENCH_PRESS,
          passed: false,
          reps: 3,
        },
        {
          name: "Разводка 35",
          count: 2,
          type: ExercisesEnum.RAZVODKA_GANTELEI_35_DEG,
          passed: false,
          reps: [10, 8],
        },
        {
          name: "Приседания со штангой",
          count: 4,
          type: ExercisesEnum.SQUATS,
          passed: false,
          reps: [10, 8, 6, 4],
        },
        {
          name: "Жим ногами",
          count: 3,
          type: ExercisesEnum.ZHIM_NOGAMI,
          passed: false,
          reps: 8,
        },
        {
          name: "Сгибание ног лежа",
          count: 4,
          type: ExercisesEnum.ZGIBANIE_NOG_LEZHA,
          passed: false,
          reps: 12,
        },
        {
          name: "Жим штанги сидя",
          count: 4,
          type: ExercisesEnum.ZHIM_SHTANGI_SIDYA,
          passed: false,
          reps: 12,
        },
      ],
    },
    {
      trainingNumber: 7,
      exercises: [
        {
          name: "Жим Лежа (65% + 10кг)",
          maxWeightCoef: 0.65 + 10,
          count: 3,
          type: ExercisesEnum.BENCH_PRESS,
          passed: false,
          reps: 10,
        },
        {
          name: "Сведения сидя",
          count: 3,
          type: ExercisesEnum.SVEDENIYA_SIDYA,
          passed: false,
          reps: 12,
        },
        {
          name: "Тяга верхнего блока",
          count: 4,
          type: ExercisesEnum.TYGA_VERHNEGO_BLOCKA,
          passed: false,
          reps: 12,
        },
        {
          name: "Хаммер",
          count: 3,
          type: ExercisesEnum.HAMMER,
          passed: false,
          reps: 10,
        },
        {
          name: "Тяга нижнего блока обратным хватом",
          count: 3,
          type: ExercisesEnum.TYAGA_NIZHNEGO_BLOCKA_OBRATNIM_HVATOM,
          passed: false,
          reps: 10,
        },
        {
          name: "Сгибание рук с гантелями",
          count: 5,
          type: ExercisesEnum.ZGIBANIE_RUK_S_GANTELYAMI,
          passed: false,
          reps: [10, 8, 8, 6, 6],
        },
      ],
    },
    {
      trainingNumber: 8,
      exercises: [
        {
          name: "Жим Лежа (75% + 10кг)",
          maxWeightCoef: 0.75 + 5,
          count: 6,
          type: ExercisesEnum.BENCH_PRESS,
          passed: false,
          reps: 5,
        },
        {
          name: "Разводка (ровно)",
          count: 3,
          type: ExercisesEnum.RAZVODKA_GANTELEI,
          passed: false,
          reps: 8,
        },
        {
          name: "Приседания со штангой",
          count: 5,
          type: ExercisesEnum.SQUATS,
          passed: false,
          reps: 12,
        },
        {
          name: "c/c Жим + Сгибания лежа",
          count: 3,
          passed: false,
          reps: 12,
        },
        {
          name: "Разводка гантелей стоя",
          count: 3,
          type: ExercisesEnum.MAHI_GANTELEI_STOYA,
          passed: false,
          reps: 10,
        },
      ],
    },
    {
      trainingNumber: 9,
      exercises: [
        {
          name: "Жим Лежа (85% + 10кг)",
          maxWeightCoef: 0.85 + 5,
          count: 10,
          type: ExercisesEnum.BENCH_PRESS,
          passed: false,
          reps: 3,
        },
        {
          name: "Сведения сидя",
          count: 2,
          type: ExercisesEnum.SVEDENIYA_SIDYA,
          passed: false,
          reps: 12,
        },
        {
          name: "Тяга штанги в наклоне",
          count: 4,
          type: ExercisesEnum.TYAGA_SHTANGI_V_NAKLONE,
          passed: false,
          reps: 8,
        },
        {
          name: "Тачка (подтягивания в тренажере)",
          count: 4,
          type: ExercisesEnum.PODTYAGIVANIA_V_TRENAZHERE,
          passed: false,
          reps: 10,
        },
        {
          name: "Тяга гантели к поясу в наклоне",
          count: 3,
          type: ExercisesEnum.TYAGA_GANTELEI_K_POYASU_V_NAKLONE,
          passed: false,
          reps: 6,
        },
        {
          name: "Поднятие штанги на бицепс обратным хватом",
          count: 4,
          type: ExercisesEnum.PODNYATIE_SHTANGI_NA_BICEPS_OBRATNIM_HVATOM,
          passed: false,
          reps: [10, 10, 8, 8],
        },
        {
          name: "Молотоки на бицепс",
          count: 3,
          type: ExercisesEnum.MOLOTKI_NA_BICEPS,
          passed: false,
          reps: "max",
        },
      ],
    },
    {
      trainingNumber: 10,
      exercises: [
        {
          name: "Жим Лежа (легкий)",
          count: 3,
          type: ExercisesEnum.BENCH_PRESS,
          passed: false,
          reps: 10,
        },
        {
          name: "Разводка (ровно)",
          count: 3,
          type: ExercisesEnum.RAZVODKA_GANTELEI,
          passed: false,
          reps: 12,
        },
        {
          name: "Фронтальный присед",
          count: 4,
          type: ExercisesEnum.FRONTALNII_PRISED,
          passed: false,
          reps: 8,
        },
        {
          name: "Румынская тяга",
          count: 3,
          type: ExercisesEnum.RUMINSKAYA_TYAGA,
          passed: false,
          reps: 10,
        },
        {
          name: "Болгарские сплит-приседы",
          count: 3,
          type: ExercisesEnum.BOLGARSKII_SPLIT_PRISED,
          passed: false,
          reps: "max",
        },
        {
          name: "21 на бицепс",
          count: 3,
          type: ExercisesEnum.BICEPS_21,
          passed: false,
          reps: 21,
        },
        {
          name: "Сгибание рук с гантелями",
          count: 4,
          type: ExercisesEnum.ZGIBANIE_RUK_S_GANTELYAMI,
          passed: false,
          reps: "max",
        },
      ],
    },
    {
      trainingNumber: 11,
      exercises: [
        {
          name: "Жим Лежа (70%)",
          maxWeightCoef: 0.7,
          count: 4,
          type: ExercisesEnum.BENCH_PRESS,
          passed: false,
          reps: 4,
        },
        {
          name: "Сведение сидя",
          count: 2,
          type: ExercisesEnum.SVEDENIYA_SIDYA,
          passed: false,
          reps: 15,
        },
        {
          name: "Становая тяга",
          count: 4,
          type: ExercisesEnum.DEAD_LIFT,
          passed: false,
          reps: 10,
        },
        {
          name: "Тяга верхнего блока",
          count: 5,
          type: ExercisesEnum.TYGA_VERHNEGO_BLOCKA,
          passed: false,
          reps: 10,
        },
        {
          name: "Тяга нижнего блока",
          count: 5,
          type: ExercisesEnum.TYAGA_NIZHNEGO_BLOCK,
          passed: false,
          reps: 10,
        },
        {
          name: "Подтягивания",
          count: 3,
          type: ExercisesEnum.PODTYAGIVANIA_V_TRENAZHERE,
          passed: false,
          reps: "max",
        },
        {
          name: "Бицепс со штангой средним хватом стоя",
          count: 4,
          type: ExercisesEnum.ZGIBANIE_RUK_SO_SHTANGOI_SREDNIM_HVATOM,
          passed: false,
          reps: 10,
        },
        {
          name: "Бицепс на скамье Скотта со штангой",
          count: 4,
          type: ExercisesEnum.BICEPS_SO_SHTANGOI_SKAMYA_SKOTTA,
          passed: false,
          reps: [12, 12, 10, 10],
        },
      ],
    },
    {
      trainingNumber: 12,
      exercises: [
        {
          name: "Жим Лежа (50%)",
          maxWeightCoef: 0.5,
          count: 1,
          type: ExercisesEnum.BENCH_PRESS,
          passed: false,
          reps: 8,
        },
        {
          name: "Жим Лежа (60%)",
          maxWeightCoef: 0.6,
          count: 1,
          type: ExercisesEnum.BENCH_PRESS,
          passed: false,
          reps: 5,
        },
        {
          name: "Жим Лежа (70%)",
          maxWeightCoef: 0.7,
          count: 1,
          type: ExercisesEnum.BENCH_PRESS,
          passed: false,
          reps: 4,
        },
        {
          name: "Жим Лежа (80%)",
          maxWeightCoef: 0.8,
          count: 1,
          type: ExercisesEnum.BENCH_PRESS,
          passed: false,
          reps: 3,
        },
        {
          name: "Жим Лежа (90%)",
          maxWeightCoef: 0.9,
          count: 1,
          type: ExercisesEnum.BENCH_PRESS,
          passed: false,
          reps: 2,
        },
        {
          name: "Жим Лежа (100%)",
          maxWeightCoef: 1,
          count: 1,
          type: ExercisesEnum.BENCH_PRESS,
          passed: false,
          reps: 1,
        },
        {
          name: "Жим Лежа (105%)",
          maxWeightCoef: 1.05,
          count: 1,
          type: ExercisesEnum.BENCH_PRESS,
          passed: false,
          reps: 1,
        },
        {
          name: "Сведения сидя",
          count: 3,
          type: ExercisesEnum.SVEDENIYA_SIDYA,
          passed: false,
          reps: 10,
        },
      ],
    },
  ],
};
