// <auto-generated />
using System;
using GymTraineeServer.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GymTraineeServer.Migrations
{
    [DbContext(typeof(PostgreSQLDbContext))]
    [Migration("20260111151024_migration_add_image_and_exercise")]
    partial class migration_add_image_and_exercise
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GymTraineeServer.Models.Database.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<byte[]>("Image")
                        .HasColumnType("bytea");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tag")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("GymTraineeServer.Models.Database.Program", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Programs");
                });

            modelBuilder.Entity("GymTraineeServer.Models.Database.TrainingDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid");

                    b.Property<int>("TrainingNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProgramId");

                    b.ToTable("TrainingDays");
                });

            modelBuilder.Entity("GymTraineeServer.Models.Database.TrainingDayToExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Count")
                        .HasColumnType("integer");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<double?>("MaxWeightCoef")
                        .HasColumnType("double precision");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean");

                    b.Property<int?>("Reps")
                        .HasColumnType("integer");

                    b.Property<Guid>("TrainingDayId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("TrainingDayId", "ExerciseId")
                        .IsUnique();

                    b.ToTable("TrainingDayToExercise");
                });

            modelBuilder.Entity("GymTraineeServer.Models.Database.TrainingDay", b =>
                {
                    b.HasOne("GymTraineeServer.Models.Database.Program", "Program")
                        .WithMany("TrainigDays")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");
                });

            modelBuilder.Entity("GymTraineeServer.Models.Database.TrainingDayToExercise", b =>
                {
                    b.HasOne("GymTraineeServer.Models.Database.Exercise", "Exercise")
                        .WithMany("TrainingDayToExercise")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymTraineeServer.Models.Database.TrainingDay", "TrainingDay")
                        .WithMany("Exercises")
                        .HasForeignKey("TrainingDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("TrainingDay");
                });

            modelBuilder.Entity("GymTraineeServer.Models.Database.Exercise", b =>
                {
                    b.Navigation("TrainingDayToExercise");
                });

            modelBuilder.Entity("GymTraineeServer.Models.Database.Program", b =>
                {
                    b.Navigation("TrainigDays");
                });

            modelBuilder.Entity("GymTraineeServer.Models.Database.TrainingDay", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
